variable "prefix" {
  type        = string
  description = "The prefix name"
}

variable "region" {
  description = "The AWS region to launch the instance in."
  default     = "us-east-1"
}

variable "profile" {
  type = string
}

variable "ami_id" {
  description = "The AMI ID to use for the instance."
  type        = string
}

variable "instance_type" {
  type        = string
  description = "The instance type to use."
  default     = "t2.micro"
}

variable "cidr_block" {
  type    = string
  default = "10.10.0.0/20"
}

variable "key_name" {
  description = "The key name to use for the instance."
  type        = string
}

variable "public_key" {
  description = "The public key to be used for the key pair."
  type        = string
}

variable "kube_version" {
  type        = string
  description = "The kubernetes version used to create cluster in minikube"
  default     = "1.27.4"
}

variable "cluster_nodes" {
  type        = number
  description = "The number of cluster nodes in minikube"
  default     = 2
}

variable "rtf_version" {
  type        = string
  description = "The runtime fabrics version to use to install rtf on tbe kube cluster"
  default     = "2.5.0"
}

variable "docker_registry" {
  type        = string
  description = "The docker registry provided by anypoint platform"
}

variable "docker_username" {
  type        = string
  description = "The docker-username generated by the anypoint platform upon RTF instance creation."
}

variable "docker_password" {
  type        = string
  description = "The docker-password generated by the anypoint platform upon RTF instance creation."
}

variable "activation_data" {
  type        = string
  description = "Activation data for the setup generated by the anypoint platform upon RTF instance creation."
}

variable "mule_license_key" {
  type        = string
  description = "MuleSoft Runtime Fabrics license key in base64."
}

